### ISSUE TITLE
Alert nearly always returns NoData with instant query type

### ISSUE THREAD

**Issue by chenlujjj** [VictoriaMetrics/victoriametrics-datasource#276]
Hi team,

recently we found that when we created grafana alert with the victoriametrics datasource and set query type as instant, the alert nearly always returns NoData.

I did some test: clicked the "Preview" button for dozens of times and checked the response of `api/v1/eval` API, it's "nodata".

![Image](https://github.com/user-attachments/assets/81acb237-7e64-4787-af25-bd6cd1ee375a)

I'm not quite sure if the issue is duplicated with https://github.com/VictoriaMetrics/victoriametrics-datasource/issues/273.

datasource version: 0.10.0
grafana version: v11.1.0
victoriametrics version: v0.109.1-cluster

**Comment by chenlujjj** [comment]
I can make sure that in the grafana explore page, the instant query always returns data.

**Comment by dmitryk-dk** [comment]
Hi @chenlujjj ! We will check it and fix it. Need to clarify that the issue is present.

**Comment by chenlujjj** [comment]
it's a user defined metric, the query is like:
```
max(A) - max(B)
```

**Comment by chenlujjj** [comment]
Seems like a related problem: I found that in the dashboard, instant query request wouldn't respect the Min interval or Min step settings.

In the following example, I set Min step as 6m, but it didn't appear in the query inspector:

<img width="1285" alt="Image" src="https://github.com/user-attachments/assets/c34c7b69-af8f-498d-92b5-05d9519a2709" />

In contrast, it worked for range query:

<img width="1349" alt="Image" src="https://github.com/user-attachments/assets/9fb29ade-4c57-482a-af73-216df1d64223" />

**Comment by chenlujjj** [comment]
Hi @dmitryk-dk To reproduce the issue, I set up an environment in my laptop from scratch:

1. deploy victoriametrics

```
docker run -d -v /tmp/victoria-metrics-data:/victoria-metrics-data -p 8428:8428 victoriametrics/victoria-metrics:v1.109.1
```

2. deploy grafana with vm datasource plugin

```
docker run -d -p 3000:3000 --name=grafana \
  -e "GF_SECURITY_ADMIN_PASSWORD=admin" \
  -e "GF_INSTALL_PLUGINS=https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/download/v0.11.1/victoriametrics-datasource-v0.11.1.zip;victoriametrics-datasource" \
  -e "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=victoriametrics-datasource" \
  grafana/grafana:11.3.0
```

3. deploy vmagent to scrape metrics and write to vm

```
docker run -d --name vmagent \
  -v $(pwd)/vmagent-config.yml:/etc/vmagent/config.yml \
  victoriametrics/vmagent \
  -promscrape.config=/etc/vmagent/config.yml \
  -remoteWrite.url=http://host.docker.internal:8428/api/v1/write
```

```
$ cat vmagent-config.yml
global:
  scrape_interval: 10s

scrape_configs:
#  - job_name: 'vmagent'
#    static_configs:
#      - targets: ['host.docker.internal:8429']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['host.docker.internal:8428']
  - job_name: 'grafana'
    static_configs:
      - targets: ['host.docker.internal:3000']
```

4. setup a simple reverse proxy in front of vm to log the request (I want to check the `step` parameter)
```
# proxy.go
package main

import (
    "bytes"
    "io/ioutil"
    "log"
    "net/http"
    "net/http/httputil"
    "net/url"
)

func main() {
    backendURL, err := url.Parse("http://localhost:8428")
    if err != nil {
        log.Fatal(err)
    }

    proxy := httputil.NewSingleHostReverseProxy(backendURL)

    http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
        logRequest(r)

        proxy.ServeHTTP(w, r)
    })

    log.Println("Starting proxy server on :8438")
    if err := http.ListenAndServe(":8438", nil); err != nil {
        log.Fatal(err)
    }
}

func logRequest(r *http.Request) {
    body, err := ioutil.ReadAll(r.Body)
    if err != nil {
        log.Printf("Error reading request body: %v", err)
        return
    }
    r.Body = ioutil.NopCloser(bytes.NewBuffer(body)) 

    log.Printf("Request Method: %s", r.Method)
    log.Printf("Request URL: %s", r.URL.String())
    log.Printf("Request Headers: %v", r.Header)
    log.Printf("Request Body: %s", body)
}

$ go run proxy.go
```


5. configure vm datasource in grafana

![Image](https://github.com/user-attachments/assets/2e168f5d-2f0c-4e8f-86f7-86d5df9421ba)



Then I created an alert rule, the query is like:

![Image](https://github.com/user-attachments/assets/1479274b-5bc8-4e7b-a656-907468c7384a)

I found that:
*  no matter I use 0.10.3 or 0.11.1 version of vm datasource, the "wide series" issue mentioned in the slack thread didn't happen. (may need further check)
* the `step` parameter is `1s`, I think it can explain why sometimes the instant query return data, other times return nodata

<img width="1448" alt="Image" src="https://github.com/user-attachments/assets/733022ad-6dcb-42f7-8dab-25b926b6e536" />

So I guess we still need to apply the fix raise by @hagen1778  for instant query:
```
step := 5m
if q.Interval > step {
  step = q.Interval
}
```

**Comment by dmitryk-dk** [comment]
Hi @chenlujjj ! The issue was fixed in the [release](https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/tag/v0.13.2). Could you check it please? 
I closed the issue. If you find any problem, feel free to reopen it

**Comment by chenlujjj** [comment]
hi @dmitryk-dk seems the issue still exists, I can reproduce it for the new v0.13.2 release.

The default interval `1s` still take effect, and is not replaced by `5m`:

<img width="1033" alt="Image" src="https://github.com/user-attachments/assets/8a856155-898a-4072-ab5f-97f29a2546b6" />

<img width="1463" alt="Image" src="https://github.com/user-attachments/assets/5632d517-fdaa-43ba-97c4-d374e9a229a3" />

**Comment by dmitryk-dk** [comment]
> hi [@dmitryk-dk](https://github.com/dmitryk-dk) seems the issue still exists, I can reproduce it for the new v0.13.2 release.
> 
> The default interval `1s` still take effect, and is not replaced by `5m`:
> 
> <img alt="Image" width="1033" src="https://private-user-images.githubusercontent.com/17081528/412708683-8a856155-898a-4072-ab5f-97f29a2546b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk0NTk0NDcsIm5iZiI6MTczOTQ1OTE0NywicGF0aCI6Ii8xNzA4MTUyOC80MTI3MDg2ODMtOGE4NTYxNTUtODk4YS00MDcyLWFiNWYtOTdmMjlhMjU0NmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjEzVDE1MDU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMWY2NzA4YTNhNDFiMjYyMzhmMDk2ZjRmZThkYzMxZjEyMzJiNjQ0OGFjZDVhYzMxMjBlODk0MDA4NGMzYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9gM-pqqCL28yC5D3Vie4FuF6De35qMBrZ5BxdCD_6QA"> <img alt="Image" width="1463" src="https://private-user-images.githubusercontent.com/17081528/412708747-5632d517-fdaa-43ba-97c4-d374e9a229a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk0NTk0NDcsIm5iZiI6MTczOTQ1OTE0NywicGF0aCI6Ii8xNzA4MTUyOC80MTI3MDg3NDctNTYzMmQ1MTctZmRhYS00M2JhLTk3YzQtZDM3NGU5YTIyOWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjEzVDE1MDU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YzlkNTU2OWZiMzc2NDVkZWZkZDdjZmYzYjM4MDQ0NzhjY2MyYzhkYmU1YTJiNmQyYWE5OWFkNzdkZTA5ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oAHYbfR79YA17Am7V7gkeOJMfpe_Kr4wbYwQ2i8ayiM">

Yeah, I found this problem and fixed it in the v0.13.3. Could you please check it?

**Comment by chenlujjj** [comment]
@dmitryk-dk  All good now, thank you !
